name: Download data from GBIF 2

on:
  push:
    branches: main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SessionInfo
        run: R -q -e 'sessionInfo()'
      - name: Install system dependencies
        run: |
      #     sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
      #     sudo apt-get update
          apt-get install -y libgdal-dev libgeos-dev libproj-dev libudunits2-dev
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('geodata', 'readr', 'dplyr', 'sf', 'jsonlite'))"

      - name: Run R script
        run: |
          Rscript R/download_data.R
