name: Download data from GBIF

on:
  push:
    branches: main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SessionInfo
        run: R -q -e 'sessionInfo()'
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libgdal-dev libgeos-dev libproj-dev libudunits2-dev
        shell: bash
      - uses: r-lib/actions/setup-renv@v2

      - name: Run R script
        run: |
          Rscript R/download_data.R

  deploy:
    runs-on: ubuntu-latest
    needs: update-data
    container:
      image: rocker/r2u:22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libgdal-dev libgeos-dev libproj-dev libudunits2-dev
        shell: bash
      - uses: r-lib/actions/setup-renv@v2
      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}
      - name: Authorize and deploy app
        env:
          APPNAME: gha_app
          ACCOUNT: ${{ secrets.RSCONNECT_USER }}
          SERVER: shinyapps.io
        run: |
          rsconnect::setAccountInfo("${{ secrets.RSCONNECT_USER }}", "${{ secrets.RSCONNECT_TOKEN }}", "${{ secrets.RSCONNECT_SECRET }}")
          rsconnect::deployApp(appName = "${{ env.APPNAME }}", account = "${{ env.ACCOUNT }}", server = "${{ env.SERVER }}")
        shell: Rscript {0}
