name: Download data from GBIF

on:
  push:
    branches: main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SessionInfo
        run: R -q -e 'sessionInfo()'
      # - name: Setup R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: '4.3.2'

      - name: Install system dependencies
        run: |
          add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          apt-get update
          apt-get install -y libgdal-dev libgeos-dev libproj-dev
      - name: Install R packages
        run: |
          Rscript -e "remotes::install_github('rspatial/terra')"
          Rscript -e "install.packages(c('geodata', 'readr', 'dplyr', 'sf', 'jsonlite'))"

      - name: Run R script
        run: |
          Rscript R/download_data.R
